### ISSUE TITLE
Production Readiness Checklist

### ISSUE THREAD

**Issue by awwong1** [udia-software/udia-server#2]
Checklist for production readiness:

- [x] 95-100% code coverage
- [x] Create User
- [x] Email confirmation
- [x] Change Password
  - [x] Audit Trail for Change Password
- [x] Reset Password
  - [x] Audit Trail for Reset Password
- [x] Change Email
  - [x] Audit Trail for Change Email
- [x] Sign In
  - [x] Track authentication attempts
- [x] Create Node
  - [x] Audit Trail For Creates
- [x] Update Node
  - [x] Audit Trail For Updates
- [x] Delete Node
  - [x] Audit Trail for Deletes
- [x] Verification of Subscription functionality
- [x] Integration of non default PubSub (redis perhaps?)
- [ ] API throttling (GraphQL depth, queries per second)

**Comment by awwong1** [comment]
Don't worry about API throttling for now. 
You don't have a client, you're on a free heroku plan, an nobody wants to use your app lol
